// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultCode int32

const (
	ResultCode_SUCCESS        ResultCode = 0
	ResultCode_UNKNOWN_FAILED ResultCode = 1
	ResultCode_NOT_A_LEADER   ResultCode = 2
)

var ResultCode_name = map[int32]string{
	0: "SUCCESS",
	1: "UNKNOWN_FAILED",
	2: "NOT_A_LEADER",
}

var ResultCode_value = map[string]int32{
	"SUCCESS":        0,
	"UNKNOWN_FAILED": 1,
	"NOT_A_LEADER":   2,
}

func (x ResultCode) String() string {
	return proto.EnumName(ResultCode_name, int32(x))
}

func (ResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{0}
}

type JoinRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PreviousIndex        uint64   `protobuf:"varint,3,opt,name=previous_index,json=previousIndex,proto3" json:"previous_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{0}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JoinRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *JoinRequest) GetPreviousIndex() uint64 {
	if m != nil {
		return m.PreviousIndex
	}
	return 0
}

type JoinResponse struct {
	Code                 ResultCode `protobuf:"varint,1,opt,name=code,proto3,enum=ResultCode" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Index                uint64     `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f4a519b878ee3b, []int{1}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetCode() ResultCode {
	if m != nil {
		return m.Code
	}
	return ResultCode_SUCCESS
}

func (m *JoinResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *JoinResponse) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterEnum("ResultCode", ResultCode_name, ResultCode_value)
	proto.RegisterType((*JoinRequest)(nil), "JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "JoinResponse")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor_41f4a519b878ee3b) }

var fileDescriptor_41f4a519b878ee3b = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xd1, 0x4b, 0xc2, 0x50,
	0x14, 0xc6, 0xdd, 0xb2, 0xa4, 0xa3, 0x8e, 0x71, 0xe9, 0x61, 0xf4, 0x92, 0x19, 0x82, 0x04, 0x4d,
	0xb0, 0xa7, 0x9e, 0xc2, 0x74, 0x91, 0x25, 0x13, 0xee, 0x92, 0xa0, 0x87, 0xc6, 0xf4, 0x1e, 0xe6,
	0x85, 0xb9, 0x3b, 0x77, 0xef, 0xa2, 0xfe, 0xfb, 0xd8, 0xd5, 0xd1, 0x9e, 0x0e, 0xdf, 0x77, 0xe0,
	0xfb, 0x9d, 0xf3, 0x81, 0xc5, 0x53, 0x85, 0x79, 0x1a, 0x25, 0x6e, 0x96, 0x0b, 0x25, 0xfa, 0x5f,
	0xd0, 0x7e, 0x15, 0x3c, 0xa5, 0xb8, 0x2f, 0x50, 0x2a, 0x62, 0x81, 0xc9, 0x99, 0x63, 0xf4, 0x8c,
	0xe1, 0x39, 0x35, 0x39, 0x23, 0x0e, 0xb4, 0x22, 0xc6, 0x72, 0x94, 0xd2, 0x31, 0xb5, 0x59, 0x49,
	0x32, 0x00, 0x2b, 0xcb, 0xf1, 0x9b, 0x8b, 0x42, 0x86, 0x3c, 0x65, 0xf8, 0xe3, 0x9c, 0xf4, 0x8c,
	0x61, 0x93, 0x76, 0x2b, 0x77, 0x5e, 0x9a, 0xfd, 0x10, 0x3a, 0x87, 0x7c, 0x99, 0x89, 0x54, 0x22,
	0xb9, 0x82, 0xe6, 0x46, 0x30, 0xd4, 0x08, 0x6b, 0xdc, 0x76, 0x29, 0xca, 0x22, 0x51, 0x53, 0xc1,
	0x90, 0xea, 0x45, 0x49, 0xdc, 0xa1, 0x94, 0x51, 0x8c, 0x15, 0xf1, 0x28, 0xc9, 0x05, 0x9c, 0xd6,
	0x41, 0x07, 0x71, 0xfb, 0x08, 0xf0, 0x9f, 0x41, 0xda, 0xd0, 0x0a, 0x56, 0xd3, 0xa9, 0x17, 0x04,
	0x76, 0x83, 0x10, 0xb0, 0x56, 0xfe, 0x9b, 0xbf, 0xfc, 0xf0, 0xc3, 0xe7, 0xc9, 0x7c, 0xe1, 0xcd,
	0x6c, 0x83, 0xd8, 0xd0, 0xf1, 0x97, 0xef, 0xe1, 0x24, 0x5c, 0x78, 0x93, 0x99, 0x47, 0x6d, 0x73,
	0xfc, 0x00, 0xf6, 0x4b, 0x14, 0xec, 0x13, 0xae, 0x70, 0x7e, 0xec, 0x86, 0x0c, 0xa0, 0x59, 0x5e,
	0x4d, 0x3a, 0x6e, 0xad, 0x9c, 0xcb, 0xae, 0x5b, 0x7f, 0xa5, 0xdf, 0x78, 0xba, 0xf9, 0xbc, 0x8e,
	0xb9, 0xda, 0x16, 0x6b, 0x77, 0x23, 0x76, 0xa3, 0x22, 0x4e, 0x7e, 0x31, 0x1f, 0x6d, 0xa3, 0x3b,
	0xa9, 0xd3, 0x46, 0xba, 0xe1, 0xf5, 0x99, 0x1e, 0xf7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6d,
	0xc8, 0xf0, 0x6b, 0x7a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HaSqliteInternalClient is the client API for HaSqliteInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HaSqliteInternalClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
}

type haSqliteInternalClient struct {
	cc *grpc.ClientConn
}

func NewHaSqliteInternalClient(cc *grpc.ClientConn) HaSqliteInternalClient {
	return &haSqliteInternalClient{cc}
}

func (c *haSqliteInternalClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/HaSqliteInternal/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HaSqliteInternalServer is the server API for HaSqliteInternal service.
type HaSqliteInternalServer interface {
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
}

// UnimplementedHaSqliteInternalServer can be embedded to have forward compatible implementations.
type UnimplementedHaSqliteInternalServer struct {
}

func (*UnimplementedHaSqliteInternalServer) Join(ctx context.Context, req *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}

func RegisterHaSqliteInternalServer(s *grpc.Server, srv HaSqliteInternalServer) {
	s.RegisterService(&_HaSqliteInternal_serviceDesc, srv)
}

func _HaSqliteInternal_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HaSqliteInternalServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HaSqliteInternal/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HaSqliteInternalServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HaSqliteInternal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "HaSqliteInternal",
	HandlerType: (*HaSqliteInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _HaSqliteInternal_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}
