// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Parameter struct {
	// Types that are valid to be assigned to Value:
	//	*Parameter_I
	//	*Parameter_D
	//	*Parameter_B
	//	*Parameter_Y
	//	*Parameter_S
	Value                isParameter_Value `protobuf_oneof:"value"`
	Name                 string            `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

type isParameter_Value interface {
	isParameter_Value()
}

type Parameter_I struct {
	I int64 `protobuf:"zigzag64,1,opt,name=i,proto3,oneof"`
}

type Parameter_D struct {
	D float64 `protobuf:"fixed64,2,opt,name=d,proto3,oneof"`
}

type Parameter_B struct {
	B bool `protobuf:"varint,3,opt,name=b,proto3,oneof"`
}

type Parameter_Y struct {
	Y []byte `protobuf:"bytes,4,opt,name=y,proto3,oneof"`
}

type Parameter_S struct {
	S string `protobuf:"bytes,5,opt,name=s,proto3,oneof"`
}

func (*Parameter_I) isParameter_Value() {}

func (*Parameter_D) isParameter_Value() {}

func (*Parameter_B) isParameter_Value() {}

func (*Parameter_Y) isParameter_Value() {}

func (*Parameter_S) isParameter_Value() {}

func (m *Parameter) GetValue() isParameter_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Parameter) GetI() int64 {
	if x, ok := m.GetValue().(*Parameter_I); ok {
		return x.I
	}
	return 0
}

func (m *Parameter) GetD() float64 {
	if x, ok := m.GetValue().(*Parameter_D); ok {
		return x.D
	}
	return 0
}

func (m *Parameter) GetB() bool {
	if x, ok := m.GetValue().(*Parameter_B); ok {
		return x.B
	}
	return false
}

func (m *Parameter) GetY() []byte {
	if x, ok := m.GetValue().(*Parameter_Y); ok {
		return x.Y
	}
	return nil
}

func (m *Parameter) GetS() string {
	if x, ok := m.GetValue().(*Parameter_S); ok {
		return x.S
	}
	return ""
}

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Parameter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Parameter_I)(nil),
		(*Parameter_D)(nil),
		(*Parameter_B)(nil),
		(*Parameter_Y)(nil),
		(*Parameter_S)(nil),
	}
}

type Statement struct {
	Sql                  string       `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Parameters           []*Parameter `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Statement) Reset()         { *m = Statement{} }
func (m *Statement) String() string { return proto.CompactTextString(m) }
func (*Statement) ProtoMessage()    {}
func (*Statement) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Statement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statement.Unmarshal(m, b)
}
func (m *Statement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statement.Marshal(b, m, deterministic)
}
func (m *Statement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statement.Merge(m, src)
}
func (m *Statement) XXX_Size() int {
	return xxx_messageInfo_Statement.Size(m)
}
func (m *Statement) XXX_DiscardUnknown() {
	xxx_messageInfo_Statement.DiscardUnknown(m)
}

var xxx_messageInfo_Statement proto.InternalMessageInfo

func (m *Statement) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *Statement) GetParameters() []*Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Request struct {
	DbId                 uint64       `protobuf:"varint,1,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty"`
	TransactionToken     uint64       `protobuf:"varint,2,opt,name=transaction_token,json=transactionToken,proto3" json:"transaction_token,omitempty"`
	Statements           []*Statement `protobuf:"bytes,3,rep,name=statements,proto3" json:"statements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetDbId() uint64 {
	if m != nil {
		return m.DbId
	}
	return 0
}

func (m *Request) GetTransactionToken() uint64 {
	if m != nil {
		return m.TransactionToken
	}
	return 0
}

func (m *Request) GetStatements() []*Statement {
	if m != nil {
		return m.Statements
	}
	return nil
}

type OpenRequest struct {
	Dsn                  string   `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenRequest) Reset()         { *m = OpenRequest{} }
func (m *OpenRequest) String() string { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()    {}
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *OpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRequest.Unmarshal(m, b)
}
func (m *OpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRequest.Marshal(b, m, deterministic)
}
func (m *OpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRequest.Merge(m, src)
}
func (m *OpenRequest) XXX_Size() int {
	return xxx_messageInfo_OpenRequest.Size(m)
}
func (m *OpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRequest proto.InternalMessageInfo

func (m *OpenRequest) GetDsn() string {
	if m != nil {
		return m.Dsn
	}
	return ""
}

type OpenResponse struct {
	DbId                 uint64   `protobuf:"varint,1,opt,name=dbId,proto3" json:"dbId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenResponse) Reset()         { *m = OpenResponse{} }
func (m *OpenResponse) String() string { return proto.CompactTextString(m) }
func (*OpenResponse) ProtoMessage()    {}
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *OpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenResponse.Unmarshal(m, b)
}
func (m *OpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenResponse.Marshal(b, m, deterministic)
}
func (m *OpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenResponse.Merge(m, src)
}
func (m *OpenResponse) XXX_Size() int {
	return xxx_messageInfo_OpenResponse.Size(m)
}
func (m *OpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenResponse proto.InternalMessageInfo

func (m *OpenResponse) GetDbId() uint64 {
	if m != nil {
		return m.DbId
	}
	return 0
}

type ExecRequest struct {
	Request              *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Timings              bool     `protobuf:"varint,2,opt,name=timings,proto3" json:"timings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecRequest) Reset()         { *m = ExecRequest{} }
func (m *ExecRequest) String() string { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()    {}
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ExecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecRequest.Unmarshal(m, b)
}
func (m *ExecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecRequest.Marshal(b, m, deterministic)
}
func (m *ExecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecRequest.Merge(m, src)
}
func (m *ExecRequest) XXX_Size() int {
	return xxx_messageInfo_ExecRequest.Size(m)
}
func (m *ExecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecRequest proto.InternalMessageInfo

func (m *ExecRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *ExecRequest) GetTimings() bool {
	if m != nil {
		return m.Timings
	}
	return false
}

type ExecResult struct {
	LastInsertId         int64    `protobuf:"varint,1,opt,name=last_insert_id,json=lastInsertId,proto3" json:"last_insert_id,omitempty"`
	RowsAffected         int64    `protobuf:"varint,2,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Time                 float64  `protobuf:"fixed64,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecResult) Reset()         { *m = ExecResult{} }
func (m *ExecResult) String() string { return proto.CompactTextString(m) }
func (*ExecResult) ProtoMessage()    {}
func (*ExecResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *ExecResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResult.Unmarshal(m, b)
}
func (m *ExecResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResult.Marshal(b, m, deterministic)
}
func (m *ExecResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResult.Merge(m, src)
}
func (m *ExecResult) XXX_Size() int {
	return xxx_messageInfo_ExecResult.Size(m)
}
func (m *ExecResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResult proto.InternalMessageInfo

func (m *ExecResult) GetLastInsertId() int64 {
	if m != nil {
		return m.LastInsertId
	}
	return 0
}

func (m *ExecResult) GetRowsAffected() int64 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

func (m *ExecResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ExecResult) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type ExecResponse struct {
	Result               []*ExecResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExecResponse) Reset()         { *m = ExecResponse{} }
func (m *ExecResponse) String() string { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()    {}
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *ExecResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResponse.Unmarshal(m, b)
}
func (m *ExecResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResponse.Marshal(b, m, deterministic)
}
func (m *ExecResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResponse.Merge(m, src)
}
func (m *ExecResponse) XXX_Size() int {
	return xxx_messageInfo_ExecResponse.Size(m)
}
func (m *ExecResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResponse proto.InternalMessageInfo

func (m *ExecResponse) GetResult() []*ExecResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type QueryRequest struct {
	Request              *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Timings              bool     `protobuf:"varint,2,opt,name=timings,proto3" json:"timings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *QueryRequest) GetTimings() bool {
	if m != nil {
		return m.Timings
	}
	return false
}

type QueryResult struct {
	Columns              []string              `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Types                []string              `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	Values               []*QueryResult_Values `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	Error                string                `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Time                 float64               `protobuf:"fixed64,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *QueryResult) Reset()         { *m = QueryResult{} }
func (m *QueryResult) String() string { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()    {}
func (*QueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *QueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResult.Unmarshal(m, b)
}
func (m *QueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResult.Marshal(b, m, deterministic)
}
func (m *QueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResult.Merge(m, src)
}
func (m *QueryResult) XXX_Size() int {
	return xxx_messageInfo_QueryResult.Size(m)
}
func (m *QueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResult proto.InternalMessageInfo

func (m *QueryResult) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *QueryResult) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *QueryResult) GetValues() []*QueryResult_Values {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *QueryResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *QueryResult) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type QueryResult_Values struct {
	Parameters           []*Parameter `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QueryResult_Values) Reset()         { *m = QueryResult_Values{} }
func (m *QueryResult_Values) String() string { return proto.CompactTextString(m) }
func (*QueryResult_Values) ProtoMessage()    {}
func (*QueryResult_Values) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9, 0}
}

func (m *QueryResult_Values) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResult_Values.Unmarshal(m, b)
}
func (m *QueryResult_Values) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResult_Values.Marshal(b, m, deterministic)
}
func (m *QueryResult_Values) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResult_Values.Merge(m, src)
}
func (m *QueryResult_Values) XXX_Size() int {
	return xxx_messageInfo_QueryResult_Values.Size(m)
}
func (m *QueryResult_Values) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResult_Values.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResult_Values proto.InternalMessageInfo

func (m *QueryResult_Values) GetParameters() []*Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type QueryResponse struct {
	Result               []*QueryResult `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResult() []*QueryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Parameter)(nil), "Parameter")
	proto.RegisterType((*Statement)(nil), "Statement")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*OpenRequest)(nil), "OpenRequest")
	proto.RegisterType((*OpenResponse)(nil), "OpenResponse")
	proto.RegisterType((*ExecRequest)(nil), "ExecRequest")
	proto.RegisterType((*ExecResult)(nil), "ExecResult")
	proto.RegisterType((*ExecResponse)(nil), "ExecResponse")
	proto.RegisterType((*QueryRequest)(nil), "QueryRequest")
	proto.RegisterType((*QueryResult)(nil), "QueryResult")
	proto.RegisterType((*QueryResult_Values)(nil), "QueryResult.Values")
	proto.RegisterType((*QueryResponse)(nil), "QueryResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xcd, 0xd6, 0x4e, 0x52, 0x4f, 0x9c, 0xaa, 0xbf, 0xed, 0xef, 0x60, 0xe5, 0x82, 0xd9, 0x16,
	0xc9, 0xa2, 0x62, 0x2b, 0xb5, 0xf0, 0x01, 0xa8, 0x40, 0x22, 0x02, 0x09, 0x58, 0x10, 0x07, 0x2e,
	0x91, 0xff, 0x6c, 0x5b, 0x0b, 0x7b, 0x9d, 0xee, 0xae, 0xdb, 0x46, 0xe2, 0xc2, 0xd7, 0xe3, 0x53,
	0xa1, 0x5d, 0x7b, 0x1b, 0x53, 0x21, 0x4e, 0x9c, 0xb2, 0x6f, 0x66, 0x32, 0xf3, 0xe6, 0xcd, 0x93,
	0x61, 0xae, 0xb8, 0xbc, 0x29, 0x73, 0x4e, 0xd7, 0xb2, 0xd1, 0x0d, 0xb9, 0x83, 0xe0, 0x43, 0x2a,
	0xd3, 0x9a, 0x6b, 0x2e, 0xf1, 0x1e, 0xa0, 0x32, 0x42, 0x31, 0x4a, 0xf0, 0x9b, 0x11, 0x43, 0xa5,
	0xc1, 0x45, 0xb4, 0x13, 0xa3, 0x04, 0x19, 0x5c, 0x18, 0x9c, 0x45, 0x5e, 0x8c, 0x92, 0x5d, 0x83,
	0x33, 0x83, 0x37, 0x91, 0x1f, 0xa3, 0x24, 0x34, 0x78, 0x63, 0xb0, 0x8a, 0xc6, 0x31, 0x4a, 0x02,
	0x83, 0x15, 0xc6, 0xe0, 0x8b, 0xb4, 0xe6, 0xd1, 0xc4, 0x84, 0x98, 0x7d, 0x9f, 0x4f, 0x61, 0x7c,
	0x93, 0x56, 0x2d, 0x27, 0x4b, 0x08, 0x3e, 0xe9, 0x54, 0xf3, 0x9a, 0x0b, 0x8d, 0xf7, 0xc1, 0x53,
	0xd7, 0x95, 0x9d, 0x1d, 0x30, 0xf3, 0xc4, 0x4f, 0x01, 0xd6, 0x8e, 0x98, 0x8a, 0x76, 0x62, 0x2f,
	0x99, 0x9d, 0x02, 0xbd, 0xe7, 0xca, 0x06, 0x59, 0x72, 0x0b, 0x53, 0xc6, 0xaf, 0x5b, 0xae, 0x34,
	0x3e, 0x80, 0x71, 0x91, 0xad, 0xca, 0xc2, 0xb6, 0xf2, 0x99, 0x5f, 0x64, 0xcb, 0x02, 0x1f, 0xc3,
	0x7f, 0x5a, 0xa6, 0x42, 0xa5, 0xb9, 0x2e, 0x1b, 0xb1, 0xd2, 0xcd, 0x37, 0x2e, 0xec, 0x5e, 0x3e,
	0xdb, 0x1f, 0x24, 0x3e, 0x9b, 0xb8, 0x19, 0xac, 0x1c, 0x2f, 0x15, 0x79, 0xfd, 0xe0, 0x7b, 0xaa,
	0x6c, 0x90, 0x25, 0x8f, 0x60, 0xf6, 0x7e, 0xcd, 0x85, 0x1b, 0xbe, 0x0f, 0x5e, 0xa1, 0x84, 0xdb,
	0xa2, 0x50, 0x82, 0x10, 0x08, 0xbb, 0x02, 0xb5, 0x6e, 0x84, 0xe2, 0x46, 0x11, 0xc3, 0x68, 0xc8,
	0x8e, 0xbc, 0x85, 0xd9, 0xeb, 0x3b, 0x9e, 0xbb, 0x26, 0x04, 0xa6, 0xb2, 0x7b, 0xda, 0xaa, 0xd9,
	0xe9, 0x2e, 0xed, 0x53, 0xcc, 0x25, 0x70, 0x04, 0x53, 0x5d, 0xd6, 0xa5, 0xb8, 0x54, 0x76, 0x8d,
	0x5d, 0xe6, 0x20, 0xf9, 0x81, 0x00, 0xba, 0x6e, 0xaa, 0xad, 0x34, 0x3e, 0x82, 0xbd, 0x2a, 0x55,
	0x7a, 0x55, 0x0a, 0xc5, 0xa5, 0x76, 0xba, 0x78, 0x2c, 0x34, 0xd1, 0xa5, 0x0d, 0x2e, 0x0b, 0x7c,
	0x08, 0x73, 0xd9, 0xdc, 0xaa, 0x55, 0x7a, 0x71, 0xc1, 0x73, 0xcd, 0xbb, 0x9b, 0x7b, 0x2c, 0x34,
	0xc1, 0x97, 0x7d, 0x0c, 0xff, 0x0f, 0x63, 0x2e, 0x65, 0x23, 0xad, 0x01, 0x02, 0xd6, 0x01, 0xb3,
	0x90, 0x2e, 0x6b, 0x6e, 0x5d, 0x80, 0x98, 0x7d, 0x93, 0x33, 0x08, 0x7b, 0x0a, 0xdd, 0xd2, 0x87,
	0x30, 0x91, 0x96, 0x4e, 0x84, 0xac, 0x9a, 0x33, 0xba, 0x65, 0xc8, 0xfa, 0x14, 0x79, 0x07, 0xe1,
	0xc7, 0x96, 0xcb, 0xcd, 0xbf, 0x91, 0xe1, 0x27, 0x82, 0x59, 0xdf, 0xce, 0xea, 0x10, 0xc1, 0x34,
	0x6f, 0xaa, 0xb6, 0x16, 0xca, 0x72, 0x08, 0x98, 0x83, 0x66, 0x2d, 0xbd, 0x59, 0xf3, 0xce, 0x62,
	0x01, 0xeb, 0x00, 0x3e, 0x86, 0x89, 0x75, 0xa9, 0x33, 0xc0, 0x01, 0x1d, 0x74, 0xa3, 0x5f, 0x6c,
	0x8a, 0xf5, 0x25, 0x5b, 0x65, 0xfc, 0x3f, 0x29, 0x33, 0xde, 0x2a, 0xb3, 0x78, 0x0e, 0x93, 0xee,
	0xbf, 0x0f, 0xec, 0x8d, 0xfe, 0x6a, 0xef, 0x17, 0x30, 0x77, 0xd3, 0x3b, 0x41, 0x8f, 0x1e, 0x08,
	0x1a, 0x0e, 0xd9, 0x39, 0x45, 0x4f, 0xbf, 0xc3, 0xce, 0xab, 0x73, 0xfc, 0x04, 0x7c, 0xe3, 0x40,
	0x1c, 0xd2, 0x81, 0x53, 0x17, 0x73, 0x3a, 0xb4, 0x25, 0x19, 0x99, 0x32, 0x73, 0x14, 0x1c, 0xd2,
	0x81, 0x17, 0x17, 0x73, 0x3a, 0x3c, 0x24, 0x19, 0xe1, 0x04, 0xc6, 0x76, 0x14, 0x9e, 0xd3, 0xe1,
	0xb5, 0x16, 0x7b, 0xf4, 0x37, 0x86, 0x64, 0x74, 0x7e, 0xf8, 0xf5, 0xf1, 0x65, 0xa9, 0xaf, 0xda,
	0x8c, 0xe6, 0x4d, 0x7d, 0xd2, 0x5e, 0x56, 0x1b, 0x2e, 0x4f, 0xae, 0xd2, 0x67, 0xea, 0xba, 0x2a,
	0x35, 0x3f, 0xb1, 0x5f, 0x9f, 0x6c, 0x62, 0x7f, 0xce, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x7f,
	0x24, 0x45, 0xec, 0x95, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DBClient is the client API for DB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DBClient interface {
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type dBClient struct {
	cc *grpc.ClientConn
}

func NewDBClient(cc *grpc.ClientConn) DBClient {
	return &dBClient{cc}
}

func (c *dBClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, "/DB/Open", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, "/DB/Exec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/DB/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBServer is the server API for DB service.
type DBServer interface {
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
}

// UnimplementedDBServer can be embedded to have forward compatible implementations.
type UnimplementedDBServer struct {
}

func (*UnimplementedDBServer) Open(ctx context.Context, req *OpenRequest) (*OpenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (*UnimplementedDBServer) Exec(ctx context.Context, req *ExecRequest) (*ExecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (*UnimplementedDBServer) Query(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

func RegisterDBServer(s *grpc.Server, srv DBServer) {
	s.RegisterService(&_DB_serviceDesc, srv)
}

func _DB_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DB/Open",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DB/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DB/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DB",
	HandlerType: (*DBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _DB_Open_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _DB_Exec_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _DB_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
